根据NMF的基本实现思路可知，目的就是 $argmin (\frac{1}{2}\sum_{i,j}(V_{ij} - (WH)_{ij})^2)$

In [1]:
import numpy as np
from sklearn.decomposition import NMF

In [2]:
V = np.array([[1,1,5,2,3], [0,6,2,1,1], [3, 4,0,3,1], [4, 1,5,6,3]])
model = NMF(n_components=2, alpha=0.01) # NMF的参数参考链接1

In [3]:
W = model.fit_transform(V)
H = model.components_

print W
print H

[[ 1.67371185  0.02013017]
 [ 0.40564826  2.17004352]
 [ 0.77627836  1.5179425 ]
 [ 2.66991709  0.00940262]]
[[ 1.32014421  0.40901559  2.10322743  1.99087019  1.29852389]
 [ 0.25859086  2.59911791  0.00488947  0.37089193  0.14622829]]


NMF的相关参考链接：
1. http://www.cnblogs.com/pinard/p/6812011.html
2. https://blog.csdn.net/acdreamers/article/details/44663421