In [1]:
import numpy as np
from scipy.sparse import csr_matrix

## 行压缩矩阵：scipy.sparse.csr_matrix(arg1, shape=None, dtype=None, copy=False)

### 构造方法

#### 1. 通过csr_matrix(data) 形式构造

**NOTE** 其中data的维度必须小于等于2

In [2]:
data = np.array([[0,1,0,2,0],[1,1,0,2,0],[2,0,5,0,0]]) 

In [3]:
arr = csr_matrix(data)

In [4]:
print type(arr)

<class 'scipy.sparse.csr.csr_matrix'>


In [5]:
print arr.toarray()

[[0 1 0 2 0]
 [1 1 0 2 0]
 [2 0 5 0 0]]


In [6]:
print arr.shape

(3, 5)


In [7]:
print arr.ndim

2


In [8]:
# 稀疏矩阵非零元素个数
print arr.nnz

7


In [9]:
# 稀疏矩阵中的元素
print arr.data

[1 2 1 1 2 2 5]


In [10]:
# 稀疏矩阵非0元素对应的列索引值所组成的数组
print arr.indices

[1 3 0 1 3 0 2]


In [11]:
# 第一个元素0，之后每隔元素表示稀疏矩阵中每行元素（非零元素）个数累计结果
print arr.indptr

[0 2 5 7]


#### 2.通过csr_matrix((data, indices, indptr), [shape=(M,N)])形式构造

In [12]:
indptr = np.array([0, 3, 5, 7, 8])
indices = np.array([0, 2, 4, 1, 3, 2, 4, 0])
data = np.array(range(1, 9))

In [13]:
arr = csr_matrix((data, indices, indptr), shape=(4, 5))

In [14]:
print arr.toarray()

[[1 0 2 0 3]
 [0 4 0 5 0]
 [0 0 6 0 7]
 [8 0 0 0 0]]


#### 3. 通过csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])形式构造
* data 表示矩阵元素
* row_ind 表示矩阵行编号
* col_ind 表示矩阵列编号

In [15]:
row = np.array([0,0,0,1,1,2,2,3])
col = np.array([0,2,4,1,3,2,4,0])
data = np.array(range(1,9))

In [16]:
arr = csr_matrix((data, (row, col)), shape=(4, 5))

In [17]:
print arr.toarray()

[[1 0 2 0 3]
 [0 4 0 5 0]
 [0 0 6 0 7]
 [8 0 0 0 0]]


**NOTE** 

* row、col、data三数组长度相等。

* 矩阵k行k列元素：a[raw_ind[k], col_ind[k]] = data[k]

#### 4. 通过csr_matrix((M,N), [dtype])形式构建空矩阵

In [18]:
arr = csr_matrix((4, 3))

In [19]:
print arr.toarray()

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [20]:
arr[0, 1] = 10

D:\Anaconda\lib\site-packages\scipy\sparse\compressed.py:730: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  SparseEfficiencyWarning)


In [21]:
print arr.toarray()

[[  0.  10.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]]


#### 5. 通过csr_matrix(S)形式构建，其中S为矩阵

In [22]:
data = np.array([0,1,0,2,3,0,5,6,0,1,0,2]).reshape(3,4)

In [23]:
arr = csr_matrix(np.matrix(data))

In [24]:
print type(arr)

<class 'scipy.sparse.csr.csr_matrix'>


In [25]:
print arr.toarray()

[[0 1 0 2]
 [3 0 5 6]
 [0 1 0 2]]
